// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TRAFO.Repositories.Repositories;

#nullable disable

namespace TRAFO.Repositories.Migrations
{
    [DbContext(typeof(EntityFrameworkDatabaseContext))]
    partial class EntityFrameworkDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("TRAFO.Repositories.Database.Entities.AccountBalanceDatabaseEntry", b =>
                {
                    b.Property<Guid>("BalanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDerived")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("BalanceId");

                    b.ToTable("AccountBalanceDatabaseEntry");
                });

            modelBuilder.Entity("TRAFO.Repositories.Database.Entities.LabelBalanceDatabaseEntry", b =>
                {
                    b.Property<Guid>("BalanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDerived")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LabelId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("BalanceId");

                    b.ToTable("LabelBalance");
                });

            modelBuilder.Entity("TRAFO.Repositories.Database.Entities.LabelCategoryBalanceDatabaseEntry", b =>
                {
                    b.Property<Guid>("BalanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDerived")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LabelCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("BalanceId");

                    b.ToTable("LabelCategoryBalance");
                });

            modelBuilder.Entity("TRAFO.Repositories.Database.Entities.LabelCategoryDatabaseEntry", b =>
                {
                    b.Property<Guid>("LabelCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LabelCategoryId");

                    b.ToTable("LabelCategorie");
                });

            modelBuilder.Entity("TRAFO.Repositories.Database.Entities.LabelDatabaseEntry", b =>
                {
                    b.Property<Guid>("LabelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DisplayId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LabelCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentLabelId")
                        .HasColumnType("TEXT");

                    b.HasKey("LabelId");

                    b.ToTable("Label");
                });

            modelBuilder.Entity("TRAFO.Repositories.Database.Entities.TransacionDatabaseEntry", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BIC")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherPartyAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherPartyName")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawData")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThisPartyAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThisPartyName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.ToTable("Transaction");
                });
#pragma warning restore 612, 618
        }
    }
}
