name: Code style

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: Release

    runs-on: ubuntu-latest 

    env:
      Solution_Name: TRAFO.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # Install dependencies
    - name: Install dependencies
      run: dotnet restore

    - name: Format
      run: dotnet format --verify-no-changes --verbosity diagnostic
